config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# :nocov:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
# :nocov:

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def owner?
    email == 'kalmathk@cs.com'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :owner_check, only: %i[ new create edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def owner_check
      redirect_to projects_path and return unless current_user&.owner?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-md-12 col-lg-8 col-xl-4 bg-white mx-auto">
    <div class="login-wrap p-4 p-md-5">
      <div class="d-flex align-items-center justify-content-center m-3">
      </div>
        <h1>Editing Project</h1>

        <%= render 'form', project: @project %>

        <hr>
        <%= link_to 'Show', @project, class: "btn btn-primary" %> 
        <%= link_to 'Back', projects_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Projects</h1>

<% if current_user %>
  <div class="row mb-2">
    <div class="col-12">
      Current user: <b><%= current_user.email%></b>
    </div>
  </div>
<% end %>

<%= link_to 'New Project', new_project_path, class: "btn btn-success" if current_user&.owner? %>

<hr>
<div class="row">
<% @projects.each do |project| %>
  <div class="col-xs-12 col-md-3 mb-2">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <%= link_to project do %>
          <h5 class="card-title"><%= project.title %></h5>
        <% end %>
        <p class="card-text"><%= project.description %></p>
        <% if current_user&.owner? %>
          <div class="row">
            <div class="col-4"></div>
            <div class="col-3">
              <%= link_to 'Edit', edit_project_path(project), class: "btn btn-primary" %>
            </div>
            <div class="col-3">
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-12 col-lg-8 col-xl-4 bg-white mx-auto">
    <div class="login-wrap p-4 p-md-5">
      <div class="d-flex align-items-center justify-content-center m-3">
      </div>
      <h1>New Project</h1>

      <%= render 'form', project: @project %>
      <hr>
      <%= link_to 'Back', projects_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12 col-lg-8 col-xl-4 bg-white mx-auto">
    <div class="login-wrap p-4 p-md-5">
      <div class="d-flex align-items-center justify-content-center m-3">
      </div>
      <small>Project name</small>
      <h2 class="mb-3"><%= @project.title %></h2>
      <small>Description</small>
      <p><%= @project.description %></p>
      <hr>
      <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-primary" if current_user&.owner? %>
      <%= link_to 'Back', projects_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Projects", projects_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <% if current_user %>
      <%= link_to("Logout", destroy_user_session_path, method: :delete, class: "nav-link") %>
    <% else %>
      <%= link_to("Sign in", new_user_session_path, class: "nav-link") %>
      <%= link_to("Sign up", new_user_registration_path, class: "nav-link") %>
    <% end%>
  </div>
</nav>